### ISSUE TITLE
How to set number picker text color dynamically 

### ISSUE THREAD

**Issue by xiachengcheng** [lany192/DateTimePicker#5]
Hi @lany192 , thanks for provider such convenient lib, but I can not find a way to change text color by code, such as setTextColor(int color) in NumberPicker in android-29.

Would you please upgrade lib to allow user to change text color?

**Comment by lany192** [comment]
numberPicker.setTextColor(Color.RED);
numberPicker.setSelectedTextColor(Color.BLACK);
